/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all goals
         * @description Returns a list of goals associated with the currently authenticated user.
         */
        get: operations["getAllGoals"];
        put?: never;
        /** Create goal */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get goal details
         * @description Returns goal details with specified Id associated with the currently authenticated user.
         */
        get: operations["getGoalDetailsById"];
        /** Update goal */
        put: operations["updateGoal"];
        post?: never;
        /** Delete goal */
        delete: operations["deleteGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todo-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all todo items
         * @description Returns a list of todo items associated with the currently authenticated user.
         */
        get: operations["getAllTodoItems"];
        put?: never;
        /** Create todo item */
        post: operations["createTodoItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todo-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get todo item
         * @description Returns todo item with specified Id associated with the currently authenticated user.
         */
        get: operations["getTodoItemById"];
        /** Update todo item */
        put: operations["updateTodoItem"];
        post?: never;
        /** Delete todo item */
        delete: operations["deleteTodoItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Model used to create a goal
         * @example {
         *       "Title": "Build and publish a full-stack side project",
         *       "LifeArea": 1,
         *       "IsActive": false,
         *       "IsSmartGoal": true,
         *       "Description": "Create a complete full-stack web application to strengthen my portfolio and improve my .NET + React skills.",
         *       "Metrics": "MVP completed; at least 3 core features implemented; deployed to production; project documented on GitHub.",
         *       "AchievabilityRationale": "I already have experience with .NET and modern frontend frameworks, and I can dedicate 5–7 hours per week.",
         *       "Motivation": "Grow as a developer, increase confidence in shipping real products, and potentially showcase it to future employers.",
         *       "DueAtUtc": "2026-03-03T17:55:00Z"
         *     }
         */
        CreateGoalPayload: {
            title: string;
            lifeArea: components["schemas"]["LifeArea"];
            isActive: boolean;
            isSmartGoal: boolean;
            description: null | string;
            metrics: null | string;
            achievabilityRationale: null | string;
            motivation: null | string;
            /** Format: date-time */
            dueAtUtc: null | string;
        };
        /**
         * @description Model used to create todo items
         * @example {
         *       "Title": "Example Title for Creation"
         *     }
         */
        CreateTodoItemPayload: {
            title: string;
        };
        /**
         * @description Represents a Goal
         * @example {
         *       "Id": "678a4f92c1a3b05f447e12f9",
         *       "Title": "Learn Aspire",
         *       "LifeArea": 1,
         *       "Status": 1,
         *       "CreatedAtUtc": "2025-11-30T17:55:00Z",
         *       "CompletedAtUtc": null,
         *       "DueAtUtc": "2026-03-03T17:55:00Z"
         *     }
         */
        Goal: {
            id: string;
            title: string;
            lifeArea: components["schemas"]["LifeArea"];
            status: components["schemas"]["GoalStatus"];
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            completedAtUtc: null | string;
            /** Format: date-time */
            dueAtUtc: null | string;
        };
        GoalResponse: {
            data: components["schemas"]["Goal"];
        };
        GoalsResponse: {
            data: components["schemas"]["Goal"][];
        };
        /** @enum {string} */
        GoalStatus: GoalStatus;
        /** @enum {string} */
        LifeArea: LifeArea;
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @description Represents a Todo item
         * @example {
         *       "Id": "679c2e4fa7b19f34d2c8f91b",
         *       "Title": "Example Title",
         *       "CreatedAtUtc": "2025-11-30T17:55:00Z",
         *       "UpdatedAtUtc": "2025-11-30T17:55:00Z",
         *       "Status": 1
         *     }
         */
        TodoItem: {
            id: string;
            title: string;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
            status: components["schemas"]["TodoItemStatus"];
        };
        TodoItemResponse: {
            data: components["schemas"]["TodoItem"];
        };
        TodoItemsResponse: {
            data: components["schemas"]["TodoItem"][];
        };
        /** @enum {string} */
        TodoItemStatus: TodoItemStatus;
        /**
         * @description Model used to update a goal
         * @example {
         *       "Id": "678a4f92c1a3b05f447e12f9",
         *       "Title": "Build and publish a full-stack side project",
         *       "LifeArea": 1,
         *       "Status": 2,
         *       "IsSmartGoal": true,
         *       "Description": "Create a complete full-stack web application to strengthen my portfolio and improve my .NET + React skills.",
         *       "Metrics": "MVP completed; 3–5 core features implemented; deployed to production; full documentation on GitHub.",
         *       "AchievabilityRationale": "I have experience with .NET and React, plus enough weekly time to work on the project.",
         *       "Motivation": "Improve my practical engineering skills and build a strong portfolio project.",
         *       "DueDate": "2026-03-03T17:55:00Z"
         *     }
         */
        UpdateGoalPayload: {
            id: string;
            title: string;
            lifeArea: components["schemas"]["LifeArea"];
            status: components["schemas"]["GoalStatus"];
            isSmartGoal: boolean;
            description: null | string;
            metrics: null | string;
            achievabilityRationale: null | string;
            motivation: null | string;
            /** Format: date-time */
            dueDate: null | string;
        };
        /**
         * @example {
         *       "Id": "679c2e4fa7b19f34d2c8f91b",
         *       "Title": "New title",
         *       "Status": 2
         *     }
         */
        UpdateTodoItemPayload: {
            id: string;
            title: string;
            status: components["schemas"]["TodoItemStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalPayload"];
                "application/*+json": components["schemas"]["CreateGoalPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getGoalDetailsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalPayload"];
                "application/*+json": components["schemas"]["UpdateGoalPayload"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getAllTodoItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoItemPayload"];
                "application/*+json": components["schemas"]["CreateTodoItemPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTodoItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoItemPayload"];
                "application/*+json": components["schemas"]["UpdateTodoItemPayload"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
export enum GoalStatus {
    NotStarted = "NotStarted",
    Active = "Active",
    OnHold = "OnHold",
    Completed = "Completed",
    Cancelled = "Cancelled"
}
export enum LifeArea {
    Career = "Career",
    Finance = "Finance",
    Health = "Health",
    FamilyAndFriends = "FamilyAndFriends",
    Relationships = "Relationships",
    PersonalGrowth = "PersonalGrowth",
    FunAndRecreation = "FunAndRecreation",
    PhysicalEnvironment = "PhysicalEnvironment"
}
export enum TodoItemStatus {
    New = "New",
    InProgress = "InProgress",
    Complete = "Complete"
}
