/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all goals
         * @description Returns a list of goals associated with the currently authenticated user.
         */
        get: operations["getAllGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todo-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all todo items
         * @description Returns a list of todo items associated with the currently authenticated user.
         */
        get: operations["getAllTodoItems"];
        put?: never;
        /** Create todo item */
        post: operations["createTodoItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todo-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get todo item
         * @description Returns todo item with specified Id associated with the currently authenticated user.
         */
        get: operations["getTodoItemById"];
        /** Update todo item */
        put: operations["updateTodoItem"];
        post?: never;
        /** Delete todo item */
        delete: operations["deleteTodoItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Model used to create todo items
         * @example {
         *       "Title": "Example Title for Creation"
         *     }
         */
        CreateTodoItemPayload: {
            title: string;
        };
        /**
         * @description Represents a Goal
         * @example {
         *       "Id": "00000000-0000-0000-0000-000000000000",
         *       "Title": "Learn Aspire",
         *       "LifeArea": 1,
         *       "Status": 1,
         *       "CreatedAt": "2025-11-30T17:55:00Z",
         *       "CompletedDate": null,
         *       "DueDate": "2026-03-03T17:55:00Z"
         *     }
         */
        Goal: {
            id: string;
            title: string;
            lifeArea: components["schemas"]["LifeArea"];
            status: components["schemas"]["GoalStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedDate: null | string;
            /** Format: date-time */
            dueDate: null | string;
        };
        GoalsResponse: {
            data: components["schemas"]["Goal"][];
        };
        /** @enum {string} */
        GoalStatus: GoalStatus;
        /** @enum {string} */
        LifeArea: LifeArea;
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @description Represents a Todo item
         * @example {
         *       "Id": "1",
         *       "Title": "Example Title",
         *       "CreatedAt": "2025-11-30T17:55:00Z",
         *       "UpdatedAt": "2025-11-30T17:55:00Z",
         *       "Status": 1
         *     }
         */
        TodoItem: {
            id: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            status: components["schemas"]["TodoItemStatus"];
        };
        TodoItemResponse: {
            data: components["schemas"]["TodoItem"];
        };
        TodoItemsResponse: {
            data: components["schemas"]["TodoItem"][];
        };
        /** @enum {string} */
        TodoItemStatus: TodoItemStatus;
        /**
         * @example {
         *       "Id": "1",
         *       "Title": "New title",
         *       "Status": 2
         *     }
         */
        UpdateTodoItemPayload: {
            id: string;
            title: string;
            status: components["schemas"]["TodoItemStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getAllTodoItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoItemPayload"];
                "application/*+json": components["schemas"]["CreateTodoItemPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTodoItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoItemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoItemPayload"];
                "application/*+json": components["schemas"]["UpdateTodoItemPayload"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteTodoItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
export enum GoalStatus {
    NotStarted = "NotStarted",
    Active = "Active",
    OnHold = "OnHold",
    Completed = "Completed",
    Cancelled = "Cancelled"
}
export enum LifeArea {
    Career = "Career",
    Finance = "Finance",
    Health = "Health",
    FamilyAndFriends = "FamilyAndFriends",
    Relationships = "Relationships",
    PersonalGrowth = "PersonalGrowth",
    FunAndRecreation = "FunAndRecreation",
    PhysicalEnvironment = "PhysicalEnvironment"
}
export enum TodoItemStatus {
    New = "New",
    InProgress = "InProgress",
    Complete = "Complete"
}
